// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcnn_fc_i144_o50.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCnn_fc_i144_o50_CfgInitialize(XCnn_fc_i144_o50 *InstancePtr, XCnn_fc_i144_o50_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCnn_fc_i144_o50_Start(XCnn_fc_i144_o50 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i144_o50_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_AP_CTRL) & 0x80;
    XCnn_fc_i144_o50_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCnn_fc_i144_o50_IsDone(XCnn_fc_i144_o50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i144_o50_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCnn_fc_i144_o50_IsIdle(XCnn_fc_i144_o50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i144_o50_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCnn_fc_i144_o50_IsReady(XCnn_fc_i144_o50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i144_o50_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCnn_fc_i144_o50_EnableAutoRestart(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i144_o50_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_AP_CTRL, 0x80);
}

void XCnn_fc_i144_o50_DisableAutoRestart(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i144_o50_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_AP_CTRL, 0);
}

void XCnn_fc_i144_o50_Set_ctrl(XCnn_fc_i144_o50 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i144_o50_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_CTRL_DATA, Data);
}

u32 XCnn_fc_i144_o50_Get_ctrl(XCnn_fc_i144_o50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i144_o50_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_CTRL_DATA);
    return Data;
}

u32 XCnn_fc_i144_o50_Get_weight_0_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_0_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_0_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_0_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_0;
}

u32 XCnn_fc_i144_o50_Get_weight_0_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_0;
}

u32 XCnn_fc_i144_o50_Write_weight_0_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_0_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_0_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_0_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_0_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_1_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_1_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_1_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_1_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_1;
}

u32 XCnn_fc_i144_o50_Get_weight_1_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_1;
}

u32 XCnn_fc_i144_o50_Write_weight_1_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_1_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_1_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_1_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_1_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_2_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_2_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_2_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_2_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_2;
}

u32 XCnn_fc_i144_o50_Get_weight_2_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_2;
}

u32 XCnn_fc_i144_o50_Write_weight_2_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_2_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_2_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_2_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_2_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_3_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_3_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_3_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_3_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_3;
}

u32 XCnn_fc_i144_o50_Get_weight_3_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_3;
}

u32 XCnn_fc_i144_o50_Write_weight_3_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_3_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_3_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_3_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_3_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_4_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_4_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_4_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_4_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_4;
}

u32 XCnn_fc_i144_o50_Get_weight_4_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_4;
}

u32 XCnn_fc_i144_o50_Write_weight_4_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_4_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_4_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_4_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_4_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_5_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_5_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_5_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_5_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_5;
}

u32 XCnn_fc_i144_o50_Get_weight_5_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_5;
}

u32 XCnn_fc_i144_o50_Write_weight_5_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_5_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_5_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_5_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_5_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_6_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_6_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_6_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_6_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_6;
}

u32 XCnn_fc_i144_o50_Get_weight_6_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_6;
}

u32 XCnn_fc_i144_o50_Write_weight_6_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_6_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_6_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_6_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_6_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_7_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_7_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_7_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_7_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_7;
}

u32 XCnn_fc_i144_o50_Get_weight_7_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_7;
}

u32 XCnn_fc_i144_o50_Write_weight_7_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_7_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_7_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_7_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_7_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_8_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_8_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_8_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_8_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_8;
}

u32 XCnn_fc_i144_o50_Get_weight_8_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_8;
}

u32 XCnn_fc_i144_o50_Write_weight_8_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_8_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_8_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_8_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_8_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_9_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_9_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_9_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_9_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_9;
}

u32 XCnn_fc_i144_o50_Get_weight_9_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_9;
}

u32 XCnn_fc_i144_o50_Write_weight_9_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_9_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_9_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_9_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_9_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_10_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_10_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_10_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_10_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_10;
}

u32 XCnn_fc_i144_o50_Get_weight_10_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_10;
}

u32 XCnn_fc_i144_o50_Write_weight_10_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_10_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_10_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_10_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_10_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_11_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_11_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_11_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_11_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_11;
}

u32 XCnn_fc_i144_o50_Get_weight_11_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_11;
}

u32 XCnn_fc_i144_o50_Write_weight_11_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_11_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_11_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_11_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_11_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_12_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_12_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_12_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_12_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_12;
}

u32 XCnn_fc_i144_o50_Get_weight_12_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_12;
}

u32 XCnn_fc_i144_o50_Write_weight_12_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_12_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_12_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_12_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_12_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_13_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_13_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_13_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_13_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_13;
}

u32 XCnn_fc_i144_o50_Get_weight_13_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_13;
}

u32 XCnn_fc_i144_o50_Write_weight_13_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_13_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_13_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_13_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_13_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_14_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_14_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_14_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_14_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_14;
}

u32 XCnn_fc_i144_o50_Get_weight_14_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_14;
}

u32 XCnn_fc_i144_o50_Write_weight_14_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_14_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_14_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_14_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_14_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_15_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_15_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_15_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_15_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_15;
}

u32 XCnn_fc_i144_o50_Get_weight_15_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_15;
}

u32 XCnn_fc_i144_o50_Write_weight_15_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_15_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_15_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_15_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_15_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_16_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_16_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_16_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_16_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_16;
}

u32 XCnn_fc_i144_o50_Get_weight_16_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_16;
}

u32 XCnn_fc_i144_o50_Write_weight_16_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_16_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_16_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_16_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_16_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_17_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_17_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_17_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_17_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_17;
}

u32 XCnn_fc_i144_o50_Get_weight_17_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_17;
}

u32 XCnn_fc_i144_o50_Write_weight_17_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_17_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_17_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_17_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_17_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_18_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_18_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_18_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_18_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_18;
}

u32 XCnn_fc_i144_o50_Get_weight_18_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_18;
}

u32 XCnn_fc_i144_o50_Write_weight_18_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_18_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_18_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_18_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_18_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_19_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_19_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_19_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_19_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_19;
}

u32 XCnn_fc_i144_o50_Get_weight_19_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_19;
}

u32 XCnn_fc_i144_o50_Write_weight_19_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_19_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_19_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_19_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_19_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_20_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_20_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_20_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_20_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_20;
}

u32 XCnn_fc_i144_o50_Get_weight_20_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_20;
}

u32 XCnn_fc_i144_o50_Write_weight_20_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_20_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_20_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_20_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_20_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_21_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_21_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_21_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_21_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_21;
}

u32 XCnn_fc_i144_o50_Get_weight_21_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_21;
}

u32 XCnn_fc_i144_o50_Write_weight_21_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_21_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_21_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_21_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_21_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_22_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_22_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_22_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_22_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_22;
}

u32 XCnn_fc_i144_o50_Get_weight_22_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_22;
}

u32 XCnn_fc_i144_o50_Write_weight_22_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_22_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_22_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_22_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_22_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_23_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_23_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_23_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_23_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_23;
}

u32 XCnn_fc_i144_o50_Get_weight_23_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_23;
}

u32 XCnn_fc_i144_o50_Write_weight_23_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_23_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_23_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_23_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_23_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_weight_24_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE);
}

u32 XCnn_fc_i144_o50_Get_weight_24_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_HIGH);
}

u32 XCnn_fc_i144_o50_Get_weight_24_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_weight_24_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_WEIGHT_24;
}

u32 XCnn_fc_i144_o50_Get_weight_24_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_WEIGHT_24;
}

u32 XCnn_fc_i144_o50_Write_weight_24_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_24_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_weight_24_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_weight_24_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_WEIGHT_24_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Get_bias_BaseAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE);
}

u32 XCnn_fc_i144_o50_Get_bias_HighAddress(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_BIAS_HIGH);
}

u32 XCnn_fc_i144_o50_Get_bias_TotalBytes(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I144_O50_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE + 1);
}

u32 XCnn_fc_i144_o50_Get_bias_BitWidth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_WIDTH_BIAS;
}

u32 XCnn_fc_i144_o50_Get_bias_Depth(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I144_O50_CTRL_DEPTH_BIAS;
}

u32 XCnn_fc_i144_o50_Write_bias_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_bias_Words(XCnn_fc_i144_o50 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I144_O50_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Write_bias_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i144_o50_Read_bias_Bytes(XCnn_fc_i144_o50 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I144_O50_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I144_O50_CTRL_ADDR_BIAS_BASE + offset + i);
    }
    return length;
}

void XCnn_fc_i144_o50_InterruptGlobalEnable(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i144_o50_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_GIE, 1);
}

void XCnn_fc_i144_o50_InterruptGlobalDisable(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i144_o50_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_GIE, 0);
}

void XCnn_fc_i144_o50_InterruptEnable(XCnn_fc_i144_o50 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCnn_fc_i144_o50_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_IER);
    XCnn_fc_i144_o50_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_IER, Register | Mask);
}

void XCnn_fc_i144_o50_InterruptDisable(XCnn_fc_i144_o50 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCnn_fc_i144_o50_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_IER);
    XCnn_fc_i144_o50_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_IER, Register & (~Mask));
}

void XCnn_fc_i144_o50_InterruptClear(XCnn_fc_i144_o50 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i144_o50_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_ISR, Mask);
}

u32 XCnn_fc_i144_o50_InterruptGetEnabled(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCnn_fc_i144_o50_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_IER);
}

u32 XCnn_fc_i144_o50_InterruptGetStatus(XCnn_fc_i144_o50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCnn_fc_i144_o50_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I144_O50_CTRL_ADDR_ISR);
}

