// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_cnn_conv_d14x14_k3x3 (
hls::stream<struct ap_axiu<32, 2, 5, 6 > >& inStream,
hls::stream<struct ap_axiu<32, 2, 5, 6 > >& outStream,
unsigned int ctrl,
unsigned int kernel[9]);
