# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/School/Project/new_repo/Vivado/autotest11/autotest11.srcs/sources_1/bd/design_1/ip/design_1_cnn_pool_d92x92_p2x2_0_0/design_1_cnn_pool_d92x92_p2x2_0_0.xci
# IP: The module: 'design_1_cnn_pool_d92x92_p2x2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/School/Project/new_repo/Vivado/autotest11/autotest11.srcs/sources_1/bd/design_1/ip/design_1_cnn_pool_d92x92_p2x2_0_0/constraints/cnn_pool_d92x92_p2x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cnn_pool_d92x92_p2x2_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/School/Project/new_repo/Vivado/autotest11/autotest11.srcs/sources_1/bd/design_1/ip/design_1_cnn_pool_d92x92_p2x2_0_0/design_1_cnn_pool_d92x92_p2x2_0_0.xci
# IP: The module: 'design_1_cnn_pool_d92x92_p2x2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/School/Project/new_repo/Vivado/autotest11/autotest11.srcs/sources_1/bd/design_1/ip/design_1_cnn_pool_d92x92_p2x2_0_0/constraints/cnn_pool_d92x92_p2x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cnn_pool_d92x92_p2x2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
