// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_my_filter_buffer (
hls::stream<struct ap_axis<32, 2, 5, 6 > >& in_stream,
hls::stream<struct ap_axis<32, 2, 5, 6 > >& out_stream,
unsigned char kernel[9],
unsigned char bias[9],
unsigned char ctrl);
