// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcnn_fc_i50_o10.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCnn_fc_i50_o10_CfgInitialize(XCnn_fc_i50_o10 *InstancePtr, XCnn_fc_i50_o10_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCnn_fc_i50_o10_Start(XCnn_fc_i50_o10 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i50_o10_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_AP_CTRL) & 0x80;
    XCnn_fc_i50_o10_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCnn_fc_i50_o10_IsDone(XCnn_fc_i50_o10 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i50_o10_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCnn_fc_i50_o10_IsIdle(XCnn_fc_i50_o10 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i50_o10_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCnn_fc_i50_o10_IsReady(XCnn_fc_i50_o10 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i50_o10_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCnn_fc_i50_o10_EnableAutoRestart(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i50_o10_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_AP_CTRL, 0x80);
}

void XCnn_fc_i50_o10_DisableAutoRestart(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i50_o10_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_AP_CTRL, 0);
}

void XCnn_fc_i50_o10_Set_ctrl(XCnn_fc_i50_o10 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i50_o10_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_CTRL_DATA, Data);
}

u32 XCnn_fc_i50_o10_Get_ctrl(XCnn_fc_i50_o10 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCnn_fc_i50_o10_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_CTRL_DATA);
    return Data;
}

u32 XCnn_fc_i50_o10_Get_weight_0_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_0_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_0_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_0_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_0;
}

u32 XCnn_fc_i50_o10_Get_weight_0_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_0;
}

u32 XCnn_fc_i50_o10_Write_weight_0_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_0_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_0_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_0_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_0_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_weight_1_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_1_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_1_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_1_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_1;
}

u32 XCnn_fc_i50_o10_Get_weight_1_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_1;
}

u32 XCnn_fc_i50_o10_Write_weight_1_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_1_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_1_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_1_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_1_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_weight_2_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_2_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_2_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_2_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_2;
}

u32 XCnn_fc_i50_o10_Get_weight_2_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_2;
}

u32 XCnn_fc_i50_o10_Write_weight_2_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_2_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_2_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_2_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_2_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_weight_3_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_3_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_3_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_3_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_3;
}

u32 XCnn_fc_i50_o10_Get_weight_3_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_3;
}

u32 XCnn_fc_i50_o10_Write_weight_3_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_3_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_3_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_3_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_3_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_weight_4_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_4_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_4_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_4_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_4;
}

u32 XCnn_fc_i50_o10_Get_weight_4_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_4;
}

u32 XCnn_fc_i50_o10_Write_weight_4_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_4_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_4_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_4_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_4_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_weight_5_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_5_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_5_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_5_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_5;
}

u32 XCnn_fc_i50_o10_Get_weight_5_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_5;
}

u32 XCnn_fc_i50_o10_Write_weight_5_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_5_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_5_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_5_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_5_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_weight_6_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_6_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_6_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_6_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_6;
}

u32 XCnn_fc_i50_o10_Get_weight_6_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_6;
}

u32 XCnn_fc_i50_o10_Write_weight_6_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_6_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_6_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_6_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_6_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_weight_7_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_7_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_7_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_7_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_7;
}

u32 XCnn_fc_i50_o10_Get_weight_7_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_7;
}

u32 XCnn_fc_i50_o10_Write_weight_7_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_7_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_7_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_7_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_7_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_weight_8_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_8_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_8_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_8_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_8;
}

u32 XCnn_fc_i50_o10_Get_weight_8_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_8;
}

u32 XCnn_fc_i50_o10_Write_weight_8_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_8_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_8_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_8_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_8_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_weight_9_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE);
}

u32 XCnn_fc_i50_o10_Get_weight_9_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_HIGH);
}

u32 XCnn_fc_i50_o10_Get_weight_9_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_weight_9_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_WEIGHT_9;
}

u32 XCnn_fc_i50_o10_Get_weight_9_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_WEIGHT_9;
}

u32 XCnn_fc_i50_o10_Write_weight_9_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_9_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_weight_9_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_weight_9_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_WEIGHT_9_BASE + offset + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Get_bias_BaseAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE);
}

u32 XCnn_fc_i50_o10_Get_bias_HighAddress(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_BIAS_HIGH);
}

u32 XCnn_fc_i50_o10_Get_bias_TotalBytes(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCNN_FC_I50_O10_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE + 1);
}

u32 XCnn_fc_i50_o10_Get_bias_BitWidth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_WIDTH_BIAS;
}

u32 XCnn_fc_i50_o10_Get_bias_Depth(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCNN_FC_I50_O10_CTRL_DEPTH_BIAS;
}

u32 XCnn_fc_i50_o10_Write_bias_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_bias_Words(XCnn_fc_i50_o10 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCNN_FC_I50_O10_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE + (offset + i)*4);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Write_bias_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XCnn_fc_i50_o10_Read_bias_Bytes(XCnn_fc_i50_o10 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCNN_FC_I50_O10_CTRL_ADDR_BIAS_HIGH - XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_BaseAddress + XCNN_FC_I50_O10_CTRL_ADDR_BIAS_BASE + offset + i);
    }
    return length;
}

void XCnn_fc_i50_o10_InterruptGlobalEnable(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i50_o10_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_GIE, 1);
}

void XCnn_fc_i50_o10_InterruptGlobalDisable(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i50_o10_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_GIE, 0);
}

void XCnn_fc_i50_o10_InterruptEnable(XCnn_fc_i50_o10 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCnn_fc_i50_o10_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_IER);
    XCnn_fc_i50_o10_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_IER, Register | Mask);
}

void XCnn_fc_i50_o10_InterruptDisable(XCnn_fc_i50_o10 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCnn_fc_i50_o10_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_IER);
    XCnn_fc_i50_o10_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_IER, Register & (~Mask));
}

void XCnn_fc_i50_o10_InterruptClear(XCnn_fc_i50_o10 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCnn_fc_i50_o10_WriteReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_ISR, Mask);
}

u32 XCnn_fc_i50_o10_InterruptGetEnabled(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCnn_fc_i50_o10_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_IER);
}

u32 XCnn_fc_i50_o10_InterruptGetStatus(XCnn_fc_i50_o10 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCnn_fc_i50_o10_ReadReg(InstancePtr->Ctrl_BaseAddress, XCNN_FC_I50_O10_CTRL_ADDR_ISR);
}

