-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fixed_point_mul is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    b : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (22 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of fixed_point_mul is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";

    signal b_read_reg_117 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter1_b_read_reg_117 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter2_b_read_reg_117 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter3_b_read_reg_117 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter4_b_read_reg_117 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter5_b_read_reg_117 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter6_b_read_reg_117 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_read_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter1_a_read_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter2_a_read_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter3_a_read_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter4_a_read_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter5_a_read_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_pipeline_reg_pp0_iter6_a_read_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_assign_fu_44_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_assign_reg_127 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_assign_fu_66_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_assign_reg_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_137 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_2_fu_30_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_38_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_52_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_60_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_74_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_88_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_cast_fu_92_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_7_fu_95_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_103_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_fu_74_ce : STD_LOGIC;

    component cnn_conv_d6x6_k3xbkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    cnn_conv_d6x6_k3xbkb_U0 : component cnn_conv_d6x6_k3xbkb
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => b_assign_reg_132,
        din1 => a_assign_reg_127,
        ce => grp_fu_74_ce,
        dout => grp_fu_74_p2);




    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                a_assign_reg_127 <= a_assign_fu_44_p3;
                a_read_reg_122 <= a;
                ap_pipeline_reg_pp0_iter1_a_read_reg_122 <= a_read_reg_122;
                ap_pipeline_reg_pp0_iter1_b_read_reg_117 <= b_read_reg_117;
                ap_pipeline_reg_pp0_iter2_a_read_reg_122 <= ap_pipeline_reg_pp0_iter1_a_read_reg_122;
                ap_pipeline_reg_pp0_iter2_b_read_reg_117 <= ap_pipeline_reg_pp0_iter1_b_read_reg_117;
                ap_pipeline_reg_pp0_iter3_a_read_reg_122 <= ap_pipeline_reg_pp0_iter2_a_read_reg_122;
                ap_pipeline_reg_pp0_iter3_b_read_reg_117 <= ap_pipeline_reg_pp0_iter2_b_read_reg_117;
                ap_pipeline_reg_pp0_iter4_a_read_reg_122 <= ap_pipeline_reg_pp0_iter3_a_read_reg_122;
                ap_pipeline_reg_pp0_iter4_b_read_reg_117 <= ap_pipeline_reg_pp0_iter3_b_read_reg_117;
                ap_pipeline_reg_pp0_iter5_a_read_reg_122 <= ap_pipeline_reg_pp0_iter4_a_read_reg_122;
                ap_pipeline_reg_pp0_iter5_b_read_reg_117 <= ap_pipeline_reg_pp0_iter4_b_read_reg_117;
                ap_pipeline_reg_pp0_iter6_a_read_reg_122 <= ap_pipeline_reg_pp0_iter5_a_read_reg_122;
                ap_pipeline_reg_pp0_iter6_b_read_reg_117 <= ap_pipeline_reg_pp0_iter5_b_read_reg_117;
                b_assign_reg_132 <= b_assign_fu_66_p3;
                b_read_reg_117 <= b;
                tmp_1_reg_137 <= grp_fu_74_p2(31 downto 10);
            end if;
        end if;
    end process;
    a_assign_fu_44_p3 <= 
        tmp_3_fu_38_p2 when (tmp_2_fu_30_p3(0) = '1') else 
        a;
    ap_return <= 
        tmp_8_fu_103_p2 when (tmp_7_fu_95_p3(0) = '1') else 
        result_cast_fu_92_p1;
    b_assign_fu_66_p3 <= 
        tmp_5_fu_60_p2 when (tmp_4_fu_52_p3(0) = '1') else 
        b;

    grp_fu_74_ce_assign_proc : process(ap_ce)
    begin
        if (not((ap_const_logic_1 = ap_ce))) then 
            grp_fu_74_ce <= ap_const_logic_0;
        else 
            grp_fu_74_ce <= ap_const_logic_1;
        end if; 
    end process;

    result_cast_fu_92_p1 <= std_logic_vector(resize(unsigned(tmp_1_reg_137),23));
    tmp_2_fu_30_p3 <= a(31 downto 31);
    tmp_3_fu_38_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(a));
    tmp_4_fu_52_p3 <= b(31 downto 31);
    tmp_5_fu_60_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(b));
    tmp_7_fu_95_p3 <= tmp_fu_88_p2(31 downto 31);
    tmp_8_fu_103_p2 <= std_logic_vector(unsigned(ap_const_lv23_0) - unsigned(result_cast_fu_92_p1));
    tmp_fu_88_p2 <= (ap_pipeline_reg_pp0_iter6_b_read_reg_117 xor ap_pipeline_reg_pp0_iter6_a_read_reg_122);
end behav;
